# =====================
# cloudbuild.yaml
# =====================

steps:
  # =====================
  # 1️⃣ Install Python dependencies
  # =====================
  - name: 'python:3.11'
    entrypoint: 'bash'
    args:
      - -c
      - |
        pip install --upgrade pip
        pip install -r app1/requirements.txt

  # =====================
  # 2️⃣ Run tests
  # =====================
  - name: 'python:3.11'
    entrypoint: 'bash'
    args:
      - -c
      - |
        echo "Running tests..."
        pytest app1/tests

  # =====================
  # 3️⃣ Build Docker Image
  # =====================
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'us-central1-docker.pkg.dev/$PROJECT_ID/app1/pythonapp1:${SHORT_SHA}',
        './app1'
      ]

  # =====================
  # 4️⃣ Trivy Image Scan (fail on HIGH/CRITICAL)
  # =====================
  - name: 'aquasec/trivy:latest'
    entrypoint: 'sh'
    args:
      - -c
      - |
        trivy image --exit-code 1 --severity HIGH,CRITICAL us-central1-docker.pkg.dev/$PROJECT_ID/app1/pythonapp1:${SHORT_SHA}

  # =====================
  # 5️⃣ Push Docker Image
  # =====================
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'us-central1-docker.pkg.dev/$PROJECT_ID/app1/pythonapp1:${SHORT_SHA}'
      ]

  # =====================
  # 6️⃣ Update Kubernetes manifests in GitHub
  # =====================

# =====================
# Options
# =====================
options:
  logging: CLOUD_LOGGING_ONLY

# =====================
# Docker Images to Track
# =====================
images:
  - "us-central1-docker.pkg.dev/$PROJECT_ID/app1/pythonapp1:${SHORT_SHA}"

# =====================
# Secrets (GitHub PAT from Secret Manager)
# =====================
