steps:
  # =====================
  # 1️⃣ Install Python dependencies
  # =====================
  - name: 'python:3.11'
    entrypoint: 'bash'
    args:
      - -c
      - |
        pip install --upgrade pip
        pip install -r app1/requirements.txt

  # =====================
  # 2️⃣ Run tests
  # =====================
  - name: 'python:3.11'
    entrypoint: 'bash'
    args:
      - -c
      - |
        echo "Running tests..."

  # =====================
  # 3️⃣ Build Docker Image
  # =====================
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'us-central1-docker.pkg.dev/$PROJECT_ID/app1/pythonapp1:${SHORT_SHA}',
        './app1'
      ]

  # =====================
  # 4️⃣ Trivy Image Scan (fail on HIGH/CRITICAL)
  # =====================
  - name: 'aquasec/trivy:latest'
    entrypoint: 'sh'
    args:
      - -c
      - |
        trivy image --exit-code 0 --severity HIGH,CRITICAL us-central1-docker.pkg.dev/$PROJECT_ID/app1/pythonapp1:${SHORT_SHA}

  # =====================
  # 5️⃣ Push Docker Image
  # =====================
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'us-central1-docker.pkg.dev/$PROJECT_ID/app1/pythonapp1:${SHORT_SHA}'
      ]

  # =====================
  # 6️⃣ Update Kubernetes manifests in GitHub
  # =====================
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    secretEnv: ['_GITHUB_TOKEN']
    args:
      - -c
      - |
        # Clone repo
        git clone https://github.com/mokadi-suryaprasad/gcpk8srepo.git
        cd gcpk8srepo

        # Configure Git
        git config --global user.email "mspr9773@gmail.com"
        git config --global user.name "M Surya Prasad"

        # Authenticate with GitHub PAT
        git remote set-url origin https://x-access-token:${_GITHUB_TOKEN}@github.com/mokadi-suryaprasad/gcpk8srepo.git

        # Checkout main
        git fetch origin main
        git checkout main

        # Update manifest and commit
        sed -i "s|image: .*|image: us-central1-docker.pkg.dev/$PROJECT_ID/app1/pythonapp1:${SHORT_SHA}|" kubernetes/deployment.yaml
        git add kubernetes/deployment.yaml
        git commit -m "Update Kubernetes manifest with image ${SHORT_SHA}" || echo "No changes to commit"
        git push origin HEAD:main

# =====================
# Options
# =====================
options:
  logging: CLOUD_LOGGING_ONLY

# =====================
# Docker Images to Track
# =====================
images:
  - "us-central1-docker.pkg.dev/$PROJECT_ID/app1/pythonapp1:${SHORT_SHA}"

# =====================
# Secrets (GitHub PAT from Secret Manager)
# =====================
availableSecrets:
  secretManager:
  - versionName: projects/gcp-zero-to-hero-467513/secrets/github-token/versions/latest
    env: _GITHUB_TOKEN
