steps:
# =========================
# 1. Install Dependencies
# =========================
- id: install-deps
  name: 'python:3.11'
  entrypoint: 'bash'
  args:
    - -c
    - |
      pip install --upgrade pip
      pip install -r app1/requirements.txt

# =========================
# 2. Run Tests
# =========================
- id: run-tests
  name: 'python:3.11'
  entrypoint: 'bash'
  args:
    - -c
    - |
      echo "Running tests (placeholder)"
      # pytest app1/tests || exit 1

# =========================
# 3. Store Build Files into GCS
# =========================
- id: upload-artifacts
  name: 'gcr.io/cloud-builders/gsutil'
  args:
    - cp
    - app1/*
    - gs://pythonapp1/

# =========================
# 4. Docker Build
# =========================
- id: docker-build
  name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t', 'us-central1-docker.pkg.dev/gcp-zero-to-hero-467513/app1/pythonapp1:${SHORT_SHA}',
    './app1'
  ]

# =========================
# 5. Trivy Image Scan
# =========================
- id: trivy-scan
  name: 'aquasec/trivy:latest'
  entrypoint: 'sh'
  args:
    - -c
    - |
      trivy image --exit-code 0 --severity HIGH,CRITICAL us-central1-docker.pkg.dev/gcp-zero-to-hero-467513/app1/pythonapp1:${SHORT_SHA}

# =========================
# 6. Push Docker Image
# =========================
- id: docker-push
  name: 'gcr.io/cloud-builders/docker'
  args: [
    'push',
    'us-central1-docker.pkg.dev/gcp-zero-to-hero-467513/app1/pythonapp1:${SHORT_SHA}'
  ]

# =========================
# 10. Commit and Push Updated Manifests (GitOps)
# =========================
- id: commit-updated-manifest
  name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args:
    - -c
    - |
      git config --global user.email "mspr9773@gmail.com"
      git config --global user.name "M Surya Prasad"
      git add kubernetes/deployment.yaml
      git commit -m "Update image to ${SHORT_SHA}"
      git push https://source.developers.google.com/p/$PROJECT_ID/r/$REPO_NAME HEAD:main


# =========================
# Options
# =========================
options:
  logging: CLOUD_LOGGING_ONLY

images:
- 'us-central1-docker.pkg.dev/gcp-zero-to-hero-467513/app1/pythonapp1:${SHORT_SHA}'
