steps:
  - name: 'python:3.11'
    entrypoint: 'bash'
    args:
      - -c
      - |
        pip install --upgrade pip
        pip install -r app1/requirements.txt

  - name: 'python:3.11'
    entrypoint: 'bash'
    args:
      - -c
      - |
        echo "Running tests..."

  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'us-central1-docker.pkg.dev/$PROJECT_ID/app1/pythonapp1:${SHORT_SHA}',
        './app1'
      ]

  - name: 'aquasec/trivy:latest'
    entrypoint: 'sh'
    args:
      - -c
      - |
        trivy image --exit-code 0 --severity HIGH,CRITICAL us-central1-docker.pkg.dev/$PROJECT_ID/app1/pythonapp1:${SHORT_SHA}

  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'us-central1-docker.pkg.dev/$PROJECT_ID/app1/pythonapp1:${SHORT_SHA}'
      ]

  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    secretEnv: ['_GITHUB_TOKEN']
    args:
      - -c
      - |
        git clone https://github.com/mokadi-suryaprasad/gcpk8srepo.git
        cd gcpk8srepo
        git config --global user.email "mspr9773@gmail.com"
        git config --global user.name "M Surya Prasad"
        git remote set-url origin https://x-access-token:${_GITHUB_TOKEN}@github.com/mokadi-suryaprasad/gcpk8srepo.git
        git fetch origin main
        git checkout main
        sed -i "s|image: .*|image: us-central1-docker.pkg.dev/$PROJECT_ID/app1/pythonapp1:${SHORT_SHA}|" kubernetes/deployment.yaml
        git add kubernetes/deployment.yaml
        git commit -m "Update Kubernetes manifest with image ${SHORT_SHA}" || echo "No changes to commit"
        git push origin HEAD:main

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - "us-central1-docker.pkg.dev/$PROJECT_ID/app1/pythonapp1:${SHORT_SHA}"

availableSecrets:
  secretManager:
  - versionName: projects/gcp-zero-to-hero-467513/secrets/github-token/versions/1
    env: _GITHUB_TOKEN
