apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-container
          image: us-central1-docker.pkg.dev/gcp-zero-to-hero-467513/app1/pythonapp1:f7de435
          ports:
            - containerPort: 8080
